### ISSUE TITLE
Bug: SMILES like `cccccc` do not work and return 500 server error

### ISSUE THREAD

**Issue by Priyansh-Kedia** [unmtransinfo/CFChemApps#12]

**Comment by Priyansh-Kedia** [comment]
This issue is mostly because we are not using `sanitize=False` while creating mol object from SMILEs
Please read [this](https://github.com/rdkit/rdkit/issues/46) discussion here for more understanding 

However, expected behaviour should be consistent by specifying explicit ways of sanitizing SMILES

**Comment by jeremyjyang** [comment]
Note that some SMILES are illegal, such as "cccccc". There can be no aromatic non-ring molecule. However, we want an error message from RDKit indicating SMILES parsing error, or whatever the RDKit exception is, not a 500 server error.

**Comment by Priyansh-Kedia** [comment]
> Note that some SMILES are illegal, such as "cccccc". There can be no aromatic non-ring molecule. However, we want an error message from RDKit indicating SMILES parsing error, or whatever the RDKit exception is, not a 500 server error.

Correct, however the DEPICT portal developed using ChemAxon does not sanitize SMILES and presents results for SMILES like `cccc`. 
Should we handle it the same way or show error about illegal SMILES?

**Comment by Jack-42** [comment]
This issue was resolved by #17
