### ISSUE TITLE
Depict app file upload menu

### ISSUE THREAD

**Issue by jeremyjyang** [unmtransinfo/CFChemApps#2]
The Depict file upload menu should support two formats, based on RDKit capabilities:

1. SMILES
2. MDL Molfile

The SMILES format is specified with some variation by Daylight, ChemAxon, and RDKit. However, at minimum we should support a file with lines which begin with SMILES, and optionally, followed by a whitespace (space or tab) and name/ID.

**Comment by Priyansh-Kedia** [comment]
@jeremyjyang I have fixed the CSV file variations as mentioned. 

I could not find multi molecule Mol Files over the internet to test the variations with MDL file. Please let me know where I can find such files to test.

Thanks

**Comment by jeremyjyang** [comment]
See the rdkit repo for lots of example files, such as https://github.com/rdkit/rdkit/blob/master/Projects/DbCLI/testData/pubchem.200.sdf, and https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/test_data/compounds.smi, and many more SMILES and MDL Molfile (SDF) format files.

**Comment by Priyansh-Kedia** [comment]
Thank you Professor

**Comment by Priyansh-Kedia** [comment]
The code is now fixed so that I can output the multiple compounds along with the structures.

**Comment by Priyansh-Kedia** [comment]
> [drugs.smi.gz](https://github.com/unmtransinfo/CFChemApps/files/11618705/drugs.smi.gz)
> 
> The app fails using the attached drugs.smi, due to the line with "CCO" and no space nor name. This should be supported. SMILES files may have only one column, just the SMILES.

The SMI and SDF files have a lot of different formats as I checked on the internet. I will confirm this in the meeting tomorrow and work on the fix

Thank you

**Comment by jeremyjyang** [comment]
Good plan. Please prioritize learning from documentation and examples from cheminformatics community/industry leaders: (1) RDKit, (2) ChemAxon, and (3) Daylight (https://www.daylight.com/), no longer in business, but inventors of SMILES.

**Comment by Jack-42** [comment]
Although it was being inferred before, pull request #17 allows for explicitly setting the file type for SMILES/MDL MolFile. We're using RDKit to read both kinds of files, which should be robust to differences in formatting (within reason). I'm going to close this as completed for now.
