### ISSUE TITLE
Help content needed

### ISSUE THREAD

**Issue by jeremyjyang** [unmtransinfo/CFChemApps#3]
The Depict app Help button should provide help. Currently, there is only placeholder text:

> Help
> 
> Demo help text

This help should describe the capabilities and guide users.

**Comment by Priyansh-Kedia** [comment]
![Screenshot 2023-05-23 at 4 20 35 PM](https://github.com/unmtransinfo/CFChemApps/assets/52661249/aed815bf-ee6a-40f7-89e6-7e007010af17)
Added help text here. 

This text can be changed as per our requirements

**Comment by Priyansh-Kedia** [comment]
![Screenshot 2023-05-23 at 4 31 35 PM](https://github.com/unmtransinfo/CFChemApps/assets/52661249/47933843-1ca8-4fc5-88d4-514530ac87ba)
Added the UNM logo along with RDKit (subject to change)

**Comment by jeremyjyang** [comment]
Done.
