### ISSUE TITLE
Logos and credits

### ISSUE THREAD

**Issue by jeremyjyang** [unmtransinfo/CFChemApps#4]
The Depict app should display some logos, particularly the UNM logo and RDKit logo, similarly to the current TID public web apps such as https://datascience.unm.edu/tomcat/biocomp/depict. Also, the help should credit the developer[s].

**Comment by Priyansh-Kedia** [comment]
![image](https://github.com/unmtransinfo/CFChemApps/assets/52661249/5c5034ef-a2db-405b-9c5e-964f8ca593b4)

Added content and images

**Comment by jeremyjyang** [comment]
Done.
