### ISSUE TITLE
SMARTS matching and highlighting

### ISSUE THREAD

**Issue by jeremyjyang** [unmtransinfo/CFChemApps#7]
For the Depict app, this is a feature request for optional input of a SMARTS, which may match a molecular sub-graph pattern of the input molecules, and can be highlighted in the image. For some example code, see https://github.com/rdkit/rdkit-tutorials/blob/master/notebooks/002_SMARTS_SubstructureMatching.ipynb.

**Comment by Priyansh-Kedia** [comment]
Added option for SMARTS in the webapp
