### ISSUE TITLE
Issue regarding .env file

### ISSUE THREAD

**Issue by Jack-42** [unmtransinfo/CFChemApps#8]
When running 'docker-compose up -d --build' the error below appears:
ERROR: Couldn't find env file: ../CFChemApps/.env.dev

I can get past the issue by just removing the 'env_file' specification from docker-compose.yml (lines 14-15). Things seem to work as expected, but I wanted to check if it was recommended to use a particular environment or if not specifying an environment will be fine.

**Comment by Priyansh-Kedia** [comment]
Hello @Jack-42 
Removing the env file requirement from the development file would create no issues for you, as we do not have any specification in the development mode. However, doing the same for production would create issues for you as the production environment contains some keys for database connection (RDS database on AWS)

We use env files to avoid hard coding the secret keys and API keys in the code itself, which helps prevent exposure of these secret keys directly. If you want to startup the production server and checkout the db connections, please let me know and I shall send you the secret keys that you need. 

To remove the issue that you faced initally (without removing the "env_file" specification in the docker-compose.yml file), you just need to create an empty file called `.env.dev` in the root directory of the project. 

Please let me know if you face any issues 

Thanks

**Comment by Jack-42** [comment]
@Priyansh-Kedia I see, thanks for the clarification. For now I can work in development mode, but I'll let you know if I end up needing the secret keys later on.
Thanks!
